name: CI
on: [ push, pull_request ]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "2.1.1"
      - name: Install Dependencies
        run: |
          poetry install
      # Update output format to enable automatic inline annotations.
      - name: Lint check
        run: poetry run ruff check --output-format=github .
      - name: Unit test
        run: poetry run pytest